version: '3'
services:
  website:
    image: roest/docker-coming-soon-generator
    environment:
      TEMPLATE: bootstrap5
      TITLE: <h4>Meridian Logistics Group Inc.</h4>
      SUBLINE: |-
        Meridian Logistics Group <br />
        admin@meridianlogisticsgroup.com <br />
        <br />
